global:
  scrape_interval: 60s
  metric_name_escaping_scheme: underscores

scrape_configs:
- job_name: otelcol
  static_configs:
  - targets:
    - otelcol:9091

- job_name: otelcol-internal
  static_configs:
  - targets:
    - otelcol:8888
